'''
Django settings for qcrbox_frontend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
'''

import logging.config
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Get environment variables
GET_ENV = os.environ.get

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The hardcoded value is a development fallback; any real deployment must set
# DJANGO_SECRET_KEY in the environment.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or \
    'django-insecure-ts$cb&@9ilx_3g2!we7v8bh7!8my^m*aq12na)aw&1@p-hsr_h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '*').split(',') if h.strip()]

# Single sign-on via Authelia: trust the Remote-User header set by the
# Traefik forwardAuth middleware. Only enable this when the frontend is
# reachable exclusively through the reverse proxy.
AUTHELIA_SSO = os.environ.get('AUTHELIA_SSO', 'False').lower() in ('true', '1', 'yes')

# Where the logout view sends users to terminate the Authelia session
# (e.g. https://auth.example.com/logout). Empty disables the redirect.
AUTHELIA_LOGOUT_URL = os.environ.get('AUTHELIA_LOGOUT_URL', '')

# The lldap web UI where users and groups are managed
# (e.g. https://users.example.com). Shown to group managers in the navbar;
# empty hides the link.
LLDAP_ADMIN_URL = os.environ.get('LLDAP_ADMIN_URL', '')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'qcrbox',
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    'dpd_static_support',
    'querystring_tag',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_plotly_dash.middleware.ExternalRedirectionMiddleware',
    'django_plotly_dash.middleware.BaseMiddleware',
]

if AUTHELIA_SSO:
    MIDDLEWARE.insert(
        MIDDLEWARE.index('django.contrib.auth.middleware.AuthenticationMiddleware') + 1,
        'core.middleware.AutheliaRemoteUserMiddleware',
    )
    AUTHENTICATION_BACKENDS = [
        # Creates Django users for authenticated Authelia usernames on first
        # visit and mirrors their group membership (and role permissions for
        # the reserved qcrbox_* groups) from the Remote-Groups header. lldap
        # is the single source of truth for users and groups; management
        # happens in its web UI, not in the frontend.
        'core.auth_backends.AutheliaRemoteUserBackend',
        # Keep the model backend so existing local accounts (e.g. the
        # superuser) can still authenticate via the admin login form.
        'django.contrib.auth.backends.ModelBackend',
    ]

# Record the acting user's username in a request-scoped contextvar so that
# outgoing QCrBox registry API calls can identify the user (X-QCrBox-User).
# Inserted after the SSO block so it runs after AutheliaRemoteUserMiddleware
# (when enabled) and after AuthenticationMiddleware in any case.
MIDDLEWARE.insert(
    MIDDLEWARE.index(
        'core.middleware.AutheliaRemoteUserMiddleware'
        if AUTHELIA_SSO
        else 'django.contrib.auth.middleware.AuthenticationMiddleware'
    ) + 1,
    'core.middleware.CurrentUserMiddleware',
)

# Honour the scheme Traefik forwarded the request with, so request.is_secure()
# and generated absolute URLs are correct behind the reverse proxy.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django_plotly_dash.finders.DashAssetFinder',
    'django_plotly_dash.finders.DashComponentFinder',
    'django_plotly_dash.finders.DashAppDirectoryFinder',
]

PLOTLY_COMPONENTS = [

    # Common components (ie within dash itself) are automatically added
    # django-plotly-dash components
    'dpd_components',
    # static support if serving local assets
    'dpd_static_support',
    # Other components, as needed
    'dash_bootstrap_components',
]

PLOTLY_DASH = {
    # Flag to control location of initial argument storage
    'cache_arguments': False,
}

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.qcrbox_auth',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_SQLITE = 'sqlite'
DB_POSTGRESQL = 'postgresql'

DATABASES_ALL = {
    DB_SQLITE: {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    DB_POSTGRESQL: {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'NAME': os.environ.get('POSTGRES_NAME', 'postgres'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
        'PORT': int(os.environ.get('POSTGRES_PORT', '5432')),
    },
}

DATABASES = {
    'default': DATABASES_ALL[os.environ.get('DJANGO_DB', DB_SQLITE)],
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Additional CSRF settings (comma-separated, e.g. https://qcrbox.example.com)
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
    ]

# Default superuser credentials

ADMIN_EMAIL = GET_ENV('DJANGO_SUPERUSER_USERNAME')
ADMIN_ACCOUNT = GET_ENV('DJANGO_SUPERUSER_USERNAME')
ADMIN_PASSWORD = GET_ENV('DJANGO_SUPERUSER_PASSWORD')

# Plotly-related settings
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Override default Django logging
LOGGING_CONFIG = None
LOGGING = {
    'version': 1,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'class':'logging.handlers.RotatingFileHandler',
            'filename': 'qcrbox.log',
            'maxBytes': 1024*1024*5, # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        '': {
            'level': 'INFO',
            'handlers': ['file'],
        },
    },
}
logging.config.dictConfig(LOGGING)

# API settings
API_BASE_URL = os.environ.get('API_BASE_URL', 'http://127.0.0.1:11000')

# Shared secret authorising the frontend to act on behalf of its users when
# calling the registry API (sent as X-QCrBox-Service-Token alongside
# X-QCrBox-User). Must match QCRBOX_SERVICE_TOKEN on the QCrBox side; when
# empty, no identity headers are sent and API calls are anonymous.
QCRBOX_SERVICE_TOKEN = os.environ.get('QCRBOX_SERVICE_TOKEN', '')

# Traefik / GUI Routing settings.
# Leave TRAEFIK_HTTP_PORT empty when QCrBox serves HTTPS on the default port
# 443; set it only for setups where the reverse proxy uses a custom port.
TRAEFIK_HTTP_PORT = os.environ.get('TRAEFIK_HTTP_PORT', '')
GUI_DOMAIN_PREFIX = os.environ.get('GUI_DOMAIN_PREFIX', '.gui.')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Allow embedding of iframes
X_FRAME_OPTIONS = 'SAMEORIGIN'

MAX_LENGTH_API_LOG = int(os.environ.get('MAX_LENGTH_API_LOG', 10000))

# Misc settings

# The time (in seconds) between automatic page refreshes when waiting for a
# calculation to finish
AUTO_REFRESH_TIME = 10
