# pylint: skip-file

# Generated by Django 5.2.1 on 2025-05-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0004_alter_filemetadata_group_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filemetadata",
            old_name="backend_id",
            new_name="backend_uuid",
        ),
        migrations.RenameField(
            model_name="processstep",
            old_name="infile_uuid",
            new_name="infile",
        ),
        migrations.RenameField(
            model_name="processstep",
            old_name="outfile_uuid",
            new_name="outfile",
        ),
    ]
