# pylint: skip-file

# Generated by Django 5.2.1 on 2025-05-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0005_rename_backend_id_filemetadata_backend_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemetadata",
            name="backend_uuid",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
