# Generated by Django 5.2.1 on 2025-05-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0006_alter_filemetadata_backend_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processstep",
            name="parent",
        ),
    ]
