# pylint: skip-file

# Generated by Django 5.2.1 on 2025-06-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0007_remove_processstep_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="filemetadata",
            name="filetype",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
