# Generated by Django 5.2.1 on 2025-06-03 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0008_process_filemetadata_filetype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processstep",
            name="application",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qcrbox.process",
            ),
        ),
    ]
