# Generated by Django 5.2.1 on 2025-06-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0009_alter_processstep_application"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Process",
            new_name="Application",
        ),
    ]
