# pylint: skip-file

# Generated by Django 5.2.1 on 2025-06-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0010_rename_process_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataPermissionSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    (
                        "edit_users",
                        "Can add, edit, delete other users, by default just within their groups.",
                    ),
                    (
                        "global_user_permissions",
                        "Can CRUD users outside of their group(s).",
                    ),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
