# Generated by Django 5.2.1 on 2025-06-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0011_datapermissionsupport"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datapermissionsupport",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    (
                        "edit_users",
                        "Can add, edit, delete other users, by default just within their groups.",
                    ),
                    ("global_access", "Can CRUD everything outside of their group(s)."),
                ),
            },
        ),
    ]
