# pylint: skip-file

# Generated by Django 5.2.1 on 2025-06-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0012_alter_datapermissionsupport_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datapermissionsupport",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    (
                        "edit_users",
                        "Can add, edit, delete other users, by default just within their groups.",
                    ),
                    (
                        "edit_data",
                        "Can edit/delete the metadata for uploaded/created files.",
                    ),
                    ("global_access", "Can CRUD everything outside of their group(s)."),
                ),
            },
        ),
    ]
