# Generated by Django 5.2.1 on 2025-06-10 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0013_alter_datapermissionsupport_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemetadata",
            name="creation_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
