# pylint: skip-file

# Generated by Django 5.2.2 on 2025-06-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0014_filemetadata_creation_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="port",
            field=models.IntegerField(default=0),
        ),
    ]
