# pylint: skip-file

# Generated by Django 5.2.2 on 2025-06-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0015_application_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
