# Generated by Django 5.2.2 on 2025-06-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0016_application_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
