# Generated by Django 5.2.2 on 2025-06-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0017_application_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="slug",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
