# pylint: skip-file

# Generated by Django 5.2.2 on 2025-06-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0018_application_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemetadata",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
