# Generated by Django 5.2.2 on 2025-06-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0019_filemetadata_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemetadata",
            name="display_filename",
            field=models.CharField(default="none", max_length=255),
            preserve_default=False,
        ),
    ]
