# Generated by Django 5.2.2 on 2025-06-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0020_filemetadata_display_filename"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datapermissionsupport",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    (
                        "edit_users",
                        "Can add, edit, delete other users, by default just within their groups.",
                    ),
                    (
                        "edit_data",
                        "Can edit/delete the metadata for uploaded/created files.",
                    ),
                    ("global_access", "Can CRUD things outside of their group(s)."),
                ),
            },
        ),
    ]
