# pylint: skip-file

# Generated by Django 5.2.2 on 2025-07-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0022_sessionreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="port",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
