# pylint: skip-file

# Generated by Django 5.2.2 on 2025-08-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0023_alter_application_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="interactive",
            field=models.BooleanField(default=True),
        ),
    ]
