# pylint: skip-file

# Generated by Django 5.2.2 on 2025-08-04 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0024_application_interactive"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="interactive",
        ),
        migrations.CreateModel(
            name="AppCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("interactive", models.BooleanField(default=False)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qcrbox.application",
                    ),
                ),
            ],
        ),
    ]
