# pylint: skip-file

# Generated by Django 5.2.2 on 2025-08-04 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0025_remove_application_interactive_appcommand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processstep",
            name="application",
        ),
        migrations.AddField(
            model_name="processstep",
            name="command",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qcrbox.appcommand",
            ),
        ),
    ]
