# pylint: skip-file

# Generated by Django 5.2.2 on 2025-08-05 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0026_remove_processstep_application_processstep_command"),
    ]

    operations = [
        migrations.AddField(
            model_name="appcommand",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="processstep",
            name="parameters",
            field=models.CharField(default="{}", max_length=255),
        ),
        migrations.AlterField(
            model_name="appcommand",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commands",
                to="qcrbox.application",
            ),
        ),
        migrations.CreateModel(
            name="CommandParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("dtype", models.CharField(max_length=127)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("required", models.BooleanField()),
                ("default", models.CharField(max_length=255)),
                (
                    "command",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="qcrbox.appcommand",
                    ),
                ),
            ],
        ),
    ]
