# pylint: skip-file

# Generated by Django 5.2.2 on 2025-08-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0027_appcommand_description_processstep_parameters_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandparameter",
            name="default",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
