# pylint: skip-file

# Generated by Django 5.2.2 on 2025-08-14 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0028_alter_commandparameter_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionreference",
            name="application",
        ),
        migrations.AddField(
            model_name="sessionreference",
            name="command",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qcrbox.appcommand",
            ),
        ),
    ]
