# pylint: skip-file

# Generated by Django 5.2.2 on 2025-08-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0029_remove_sessionreference_application_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commandparameter",
            name="validation_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="commandparameter",
            name="validation_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
