# pylint: skip-file

# Generated by Django 5.2.6 on 2025-10-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcrbox", "0030_commandparameter_validation_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appcommand",
            name="description",
            field=models.TextField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="description",
            field=models.TextField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name="commandparameter",
            name="description",
            field=models.TextField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name="commandparameter",
            name="dtype",
            field=models.CharField(max_length=255),
        ),
    ]
