# Generated by Django 5.2.7 on 2026-07-15 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcrbox', '0031_alter_appcommand_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file_id', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=32)),
                ('filename', models.CharField(max_length=255)),
                ('process_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='qcrbox.processstep')),
            ],
        ),
    ]
