'''
Extension of template tags provided with the Django Plotly Dash library
to provide more control over the properties of html components generated
as part of serving dash content on django web pages.

'''

# pylint: disable=too-many-arguments, unused-variable, unused-argument, possibly-unused-variable

from django import template

from django_plotly_dash.templatetags import plotly_dash as plotly_dash_tags

register = template.Library()

@register.inclusion_tag("django_plotly_dash_custom/plotly_app.html", takes_context=True)
def plotly_app_custom(context, div_id='plotly_div', iframe_id='plotly_iframe', **kwargs):
    '''A wrapper for the django_plotly_dash plotly_app template tag to also
    allow setting id values for the iframe and its containing div generated by
    that tag.
    '''

    dash_args = plotly_dash_tags.plotly_app(context, **kwargs)
    dash_args['div_id'] = div_id
    dash_args['iframe_id'] = iframe_id
    return dash_args
